### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by othnielussher** [dhruvpatidar359/Fluttersnips#13]
The pull request (#11) had runtime errors when you navigate to the Layouts tab.

`Another exception was thrown: Incorrect use of ParentDataWidget.`

Do check the console for logs when you execute `flutter run`.

**Comment by dhruvpatidar359** [comment]
i have resolved it in the updated code , don't worry , this error is due to covering of expand widget with clipRect . As we can only cover a expand with Flex . The code for our particular card contains a clipRect under that we have contentWidget . So i have removed the expand and it is working fine.
